name: financial_wellness_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.4
  flutter_bloc: ^8.1.2
  go_router: ^14.3.0
  get_it: ^7.2.0
  intl: ^0.19.0
  intl_utils: ^2.8.10
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  template_arbs:
    - lib/l10n/intl_en.arb
    - lib/l10n/intl_es.arb
  output_dir: lib/l10n/generated